web/apps/urls.py
# coding=utf-8
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from apps.dashboard.views import IndexView
from core.adminlte.views import ChangePasswordView, \
    ChangePasswordDoneView
from django.views.static import serve
from core.adminlte import views
# 基础 url
urlpatterns = [
    url('^page/change-password/$', ChangePasswordView.as_view(),
        name='change_password'),
    url('^page/change-password-done/$', ChangePasswordDoneView.as_view(),
        name='password_change_done'),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^management/$', login_required(views.IndexView.as_view()), name='manage'),
    url(r'^$', login_required(IndexView.as_view()), name='index'),

    url(r'^auth/', include("core.registration.urls",
                           namespace="registration")),

    url(r'^jsreverse/$', 'django_js_reverse.views.urls_js', name='js_reverse'),
]

# ===================== 自定义url映射 开始====================================
# 自定义url必须放在通用url的前面，将通用url覆盖掉
# Page url
urlpatterns += [
    url(r'^apps/tasks/', include('apps.tasks.urls', namespace='tasks')),
]
# API url
urlpatterns += [
    url(r'^api/', include('apps.api.urls', namespace='api')),
    url(r'^api/v1/messageset', include('core.messageset.urls_api',
                                       namespace='messageset_api')),
    # # url(r'^api/v1/organization', include('organization.urls',
    # namespace='organization_api')),
]

# ===================== 自定义url映射 结束 ==================================

# # 通用URL映射，必须放在最后
urlpatterns += [
    # 通用页面URL映射，必须放在最后
    url(r'^management', include('core.adminlte.urls', namespace='adminlte')),
    url(r'^api/v1', include('core.adminlte.urls_api',
                             namespace='adminlte_api')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        url(r'^page_images/(?P<path>.*)$', serve, {
            'document_root': '/data/share/dzj_characters/page_images',
        }),

    ]

web/core/adminlte/urls.py
# coding=utf-8
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from core.adminlte.views import CommonListPageView, \
    CommonCreatePageView, CommonUpdatePageView, CommonDeletePageView, \
    CommonDetailPageView, CommonExportPageView, CommonImportPageView


urlpatterns = [
    url(r'/403.html', TemplateView.as_view(template_name='adminlte/403.html'),
        name='http403'),

    url(r'/(?P<app_name>\w+)/(?P<model_name>\w+)/list$',
        login_required(CommonListPageView.as_view()),
        name='common_list_page'),

    url(r'/(?P<app_name>\w+)/(?P<model_name>\w+)/export$',
        login_required(CommonExportPageView.as_view()),
        name='common_export_page'),

    url(r'/(?P<app_name>\w+)/(?P<model_name>\w+)/import$',
        login_required(CommonImportPageView.as_view()),
        name='common_import_page'),

    url(r'/(?P<app_name>\w+)/(?P<model_name>\w+)/create$',
        login_required(CommonCreatePageView.as_view()),
        name='common_create_page'),

    url(r'/(?P<app_name>\w+)/(?P<model_name>\w+)/detail/(?P<pk>\d+)$',
        login_required(CommonDetailPageView.as_view()),
        name='common_detail_page'),

    url(r'/(?P<app_name>\w+)/(?P<model_name>\w+)/update/(?P<pk>\d+)$',
        login_required(CommonUpdatePageView.as_view()),
        name='common_update_page'),

    url(r'/(?P<app_name>\w+)/(?P<model_name>\w+)/delete$',
        login_required(CommonDeletePageView.as_view()),
        name='common_delete_page'),

    # url(r'/page/(?P<app_name>\w+)/(?P<model_name>\w+)/form.html$',
    # TemplateView.as_view(template_name='adminlte/system/config.html'),
    #     name='common_form'),
    #
    # url(r'/page/adminlte/SystemConfig.html$',
    #     TemplateView.as_view(template_name='adminlte/system/config.html'),
    #     name='systemconfig'),
    # url(r'/system/config/form.html$', SystemConfigFormView.as_view(),
    #     name='systemconfig_form'),
    #
    # url(r'/system/role.html$', SiteMailListView.as_view(),
    #     name='role'),
    # url(r'/system/auth.html$', SiteMailListView.as_view(),
    #     name='auth'),
    # url(r'/system/user.html$', SiteMailListView.as_view(),
    #     name='user'),
    #
    # url(r'/page/adminlte/SiteMail.html$', SiteMailListView.as_view(),
    #     name='sitemail'),
    # url(r'/notification.html$', NotificationListView.as_view(),
    #     name='notification'),
    # url(r'/task.html$', TaskListView.as_view(),
    #     name='task'),
]

web/core/registration/urls.py
# coding=utf-8

from django.conf.urls import url
from core.registration import views

urlpatterns = [
    # sessions
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    # register, 暂不开放注册
    # url(r'^register/$', views.RegisterView.as_view(), name='register'),
    # url(r'^register/success/$', views.RegisterSuccessView.as_view(),
    # name='register-success')

]

web/core/adminlte/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals
from django import forms

web/core/adminlte/views.py
# coding=utf-8
import xlwt

from django.contrib.auth import views

from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse
from django.http import HttpResponse, JsonResponse
from django.views.generic import ListView, CreateView, \
    UpdateView, DeleteView, TemplateView, DetailView
from core.adminlte import constants
from core.adminlte.models import SystemConfig
from core.organization.models import Staff


def get_app_model_name(kwargs):
    app_name = kwargs.get('app_name').lower()
    model_name = kwargs.get('model_name').lower()
    return app_name, model_name


def get_model_content_type(app_name, model_name):
    return ContentType.objects.get(app_label=app_name, model=model_name)


def get_system_config_value(key_name):
    try:
        return SystemConfig.objects.get(name=key_name).value
    except:
        return u'未找到 %s 系统配置项' % key_name


class CommonPageViewMixin(object):
    def get_context_data(self, **kwargs):
        context = super(CommonPageViewMixin, self).get_context_data(**kwargs)
        default_dashboard_title = constants.DEFAULT_DASHBOARD_TITLE
        if hasattr(self, 'model'):
            page_title = self.model._meta.verbose_name
        else:
            page_title = default_dashboard_title

        common_dict = {
            'default_dashboard_title': default_dashboard_title,
            'page_title': page_title,
            'page_model': getattr(self, 'model', ''),
            'page_app_name': getattr(self, 'app_name', ''),
            'page_model_name': getattr(self, 'model_name', ''),
            'page_system_name': get_system_config_value('system_name'),
            'page_system_subhead': get_system_config_value('system_subhead')
        }
        context.update(common_dict)
        return context


class IndexView(CommonPageViewMixin, TemplateView):
    template_name = "adminlte/index.html"

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        staff_count = Staff.objects.filter(status=Staff.VALID).count()
        context['staff_count'] = staff_count
        return context


class ChangePasswordView(CommonPageViewMixin, TemplateView):
    def post(self, request, **kwargs):
        self.request = request
        context = super(ChangePasswordView, self).get_context_data(**kwargs)
        return self.render_to_response(context)

    def render_to_response(self, context, **response_kwargs):
        context['page_title'] = u'修改密码'
        template_response = views.password_change(
            self.request,
            template_name='adminlte/change-password.html',
            extra_context=context
        )
        return template_response


class ChangePasswordDoneView(CommonPageViewMixin, TemplateView):
    template_name = 'adminlte/change-password-done.html'


class CommonListPageView(CommonPageViewMixin, ListView):
    template_name = 'adminlte/common_list.html'

    def get(self, request, *args, **kwargs):
        self.app_name, self.model_name = get_app_model_name(kwargs)
        model_type = get_model_content_type(self.app_name, self.model_name)
        self.model = model_type.model_class()
        if hasattr(self.model.Config, 'list_template_name'):
            self.template_name = self.model.Config.list_template_name
        return super(CommonListPageView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(CommonListPageView, self).get_context_data(**kwargs)
        titles, fields = self.get_table_titles()
        context['table_titles'] = titles
        context['table_fields'] = list(fields)
        return context

    def get_table_titles(self):
        show_fields = self.model.Config.list_display_fields
        meta_fields = self.model._meta.fields
        meta_names = [mf.name for mf in meta_fields]
        titles = []
        for name in show_fields:
            if name not in meta_names:
                try:
                    t = getattr(self.model, name).field.verbose_name
                except:
                    t = u'关联'
                titles.append(t)
            for mf in meta_fields:
                if mf.name == name:
                    titles.append(mf.verbose_name)
        return titles, show_fields

class CommonExportPageView(CommonPageViewMixin, ListView):
    template_name = 'adminlte/common_list.html'

    def get(self, request, *args, **kwargs):
        self.app_name, self.model_name = get_app_model_name(kwargs)
        model_type = get_model_content_type(self.app_name, self.model_name)
        self.model = model_type.model_class()
        meta_fields = self.model._meta.fields
        columns = [mf.name for mf in meta_fields]
        # if hasattr(self.model.Config, 'list_display_fields'):
        #     columns = self.model.Config.list_display_fields
        response = HttpResponse(content_type='application/ms-excel')
        response['Content-Disposition'] = 'attachment; filename="'+ self.model_name + '.xls"'

        wb = xlwt.Workbook(encoding='utf-8')
        ws = wb.add_sheet(self.model_name)

        # Sheet header, first row
        row_num = 0

        font_style = xlwt.XFStyle()
        font_style.font.bold = True

        for col_num in range(len(columns)):
            name = columns[col_num]
            t = self.model._meta.get_field_by_name(name)[0].verbose_name
            ws.write(row_num, col_num, t, font_style)

        # Sheet body, remaining rows
        font_style = xlwt.XFStyle()

        rows = self.model.objects.all().values_list(*columns)
        for row in rows:
            row_num += 1
            for col_num in range(len(row)):
                ws.write(row_num, col_num, row[col_num], font_style)

        wb.save(response)
        return response


class CommonImportPageView(CommonPageViewMixin, TemplateView):

    def get(self, request, *args, **kwargs):
        self.app_name, self.model_name = get_app_model_name(kwargs)
        model_type = get_model_content_type(self.app_name, self.model_name)
        self.model = model_type.model_class()
        context = super(CommonImportPageView, self).get_context_data(**kwargs)
        context['page_title'] = u'导入{0}'.format(self.model._meta.verbose_name)
        context['result'] = None
        return self.render_to_response(context)

    def render_to_response(self, context, **response_kwargs):
        template_response = views.password_change(
            self.request,
            template_name='adminlte/common_import.html',
            extra_context=context
        )
        return template_response

    def post(self, request, *args, **kwargs):
        context = super(CommonImportPageView, self).get_context_data(**kwargs)
        self.app_name, self.model_name = get_app_model_name(kwargs)
        model_type = get_model_content_type(self.app_name, self.model_name)
        self.model = model_type.model_class()
        context['page_title'] = u'导入{0}'.format(self.model._meta.verbose_name)
        f = request.FILES['file']
        ret, msg = self.model.import_from_xls(f)
        context['result'] = ret
        context['msg'] = msg
        return self.render_to_response(context)

class CommonFormPageMixin(CommonPageViewMixin):
    template_name = 'adminlte/common_form.html'

    def set_form_page_attributes(self, *args, **kwargs):
        self.app_name, self.model_name = get_app_model_name(kwargs)
        model_type = get_model_content_type(self.app_name, self.model_name)
        self.model = model_type.model_class()
        self.fields = getattr(self.model.Config, 'list_form_fields', ())
        if hasattr(self.model.Config, 'success_url'):
            self.success_url = self.model.Config.success_url
        else:
            self.success_url = reverse(
                'adminlte:common_list_page',
                kwargs={
                    'app_name': self.app_name,
                    'model_name': self.model_name
                }
            )
        if hasattr(self.model.Config, 'form_template_name'):
            self.template_name = getattr(self.model.Config,
                                         'form_template_name')


class CommonCreatePageView(CommonFormPageMixin, CreateView):
    def get(self, request, *args, **kwargs):
        self.object = None
        self.set_form_page_attributes(*args, **kwargs)
        resp = super(CommonCreatePageView, self).get(request, *args, **kwargs)
        return resp

    def form_valid(self, form):
        form.instance.creator = self.request.user
        return super(CommonCreatePageView, self).form_valid(form)

    def post(self, request, *args, **kwargs):
        self.set_form_page_attributes(*args, **kwargs)
        return super(CommonCreatePageView, self).post(request, *args, **kwargs)


class CommonDetailPageView(CommonPageViewMixin, DetailView):
    template_name = 'adminlte/common_detail.html'

    def get(self, request, *args, **kwargs):
        self.app_name, self.model_name = get_app_model_name(kwargs)
        model_type = get_model_content_type(self.app_name, self.model_name)
        self.model = model_type.model_class()
        if hasattr(self.model.Config, 'detail_template_name'):
            self.template_name = self.model.Config.detail_template_name
        return super(CommonDetailPageView, self).get(request, *args, **kwargs)

    def get_object(self, queryset=None):
        obj = super(CommonDetailPageView, self).get_object(queryset)
        if hasattr(self.model.Config, 'get_object_hook'):
            self.model.Config.get_object_hook(self.request, obj)
        return obj


class CommonUpdatePageView(CommonFormPageMixin, UpdateView):
    def get_queryset(self):
        pk = self.kwargs.get('pk')
        self.set_form_page_attributes(*self.args, **self.kwargs)
        return self.model.objects.filter(pk=pk)


class CommonDeletePageView(CommonFormPageMixin, DeleteView):
    def delete(self, request, *args, **kwargs):

web/core/adminlte/templates/adminlte/includes/control_sidebar.html
<aside class="control-sidebar control-sidebar-light">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
        <li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
        <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
        <!-- Home tab content -->
        <div class="tab-pane active" id="control-sidebar-home-tab">
            <h3 class="control-sidebar-heading">Recent Activity</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript::;">
                        <i class="menu-icon fa fa-birthday-cake bg-red"></i>

                        <div class="menu-info">
                            <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                            <p>Will be 23 on April 24th</p>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->

            <h3 class="control-sidebar-heading">Tasks Progress</h3>
            <ul class="control-sidebar-menu">
                <li>
                    <a href="javascript::;">
                        <h4 class="control-sidebar-subheading">
                            Custom Template Design
                            <span class="label label-danger pull-right">70%</span>
                        </h4>

                        <div class="progress progress-xxs">
                            <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                        </div>
                    </a>
                </li>
            </ul>
            <!-- /.control-sidebar-menu -->

        </div>
        <!-- /.tab-pane -->
        <!-- Stats tab content -->
        <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
        <!-- /.tab-pane -->
        <!-- Settings tab content -->
        <div class="tab-pane" id="control-sidebar-settings-tab">
            <form method="post">
                <h3 class="control-sidebar-heading">General Settings</h3>

                <div class="form-group">
                    <label class="control-sidebar-subheading">
                        Report panel usage
                        <input type="checkbox" class="pull-right" checked/>
                    </label>
                    <p>
                        Some information about this general settings option
                    </p>
                </div>
                <!-- /.form-group -->
            </form>
        </div>
        <!-- /.tab-pane -->
    </div>
</aside>
<div class="control-sidebar-bg"></div>

web/core/adminlte/templates/adminlte/includes/footer.html
<!-- Main Footer -->
<footer class="main-footer">
    <!-- To the right -->
    <div class="pull-right hidden-xs">
        {{ page_system_subhead }}
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2016
        <a href="#">{{ page_system_name }}</a>
    </strong>
</footer>

web/core/adminlte/templates/adminlte/includes/footer_script.html
{% load static %}
<input type="hidden" name="adminlte_page_app_name" id="adminlte_page_app_name"
       value="{{ page_app_name }}"/>
<input type="hidden" name="adminlte_page_model_name" id="adminlte_page_model_name"
       value="{{ page_model_name }}"/>
<input type="hidden" name="adminlte_page_user_name" id="adminlte_page_user_name"
       value="{{ request.user.username }}"/>
<script src="{% static 'plugins/jQuery/jQuery-2.1.4.min.js' %}"
        type="text/javascript"></script>
<script src="{% static 'plugins/bootstrap/js/bootstrap.min.js' %}"
        type="text/javascript"></script>
<script src="{% static 'plugins/underscore/underscore-min.js' %}"
        type="text/javascript"></script>
<script src="{% static 'plugins/underscore/underscore.string.min.js' %}"
        type="text/javascript"></script>
<script src="{% static 'plugins/vue/dist/vue.min.js' %}"
        type="text/javascript"></script>
<script src="{% static 'plugins/sweetalert/dist/sweetalert.min.js' %}"
        type="text/javascript"></script>
<script src="{% url 'js_reverse' %}" type="text/javascript"></script>

<script src="{% static 'plugins/jsdiff/diff.js' %}"
        type="text/javascript"></script>

<!-- AdminLTE App -->
<script src="{% static 'adminlte/js/app.min.js' %}"
        type="text/javascript"></script>
<!-- 全局配置 -->
<script src="{% static 'adminlte/js/config.js' %}"
        type="text/javascript"></script>
<!-- 全局ajax -->
<script src="{% static 'adminlte/js/ajax.js' %}"
        type="text/javascript"></script>
<!-- app js -->
<script src="{% static 'messageset/js/messageset.js' %}"
        type="text/javascript"></script>

web/core/adminlte/templates/adminlte/includes/header.html
<header class="main-header">
    {% block branding %}
        <a href="{% url 'index' %}" class="logo">
            <span class="logo-mini">{{ page_system_name|first }}</span>
            <span class="logo-lg">{{ page_system_name }}</span>
        </a>
    {% endblock %}

    <nav class="navbar navbar-static-top" role="navigation">
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">切换菜单</span>
        </a>

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav" id="messagesetVue">
                {% include "adminlte/includes/header_sitemails.html" %}

                {% include "adminlte/includes/header_notifications.html" %}

                {% include "adminlte/includes/header_tasks.html" %}

                {% include "adminlte/includes/header_account.html" %}
{#                <li>#}
{#                    <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>#}
{#                </li>#}
            </ul>
        </div>
    </nav>
</header>

web/core/adminlte/templates/adminlte/includes/header_account.html
<li class="dropdown user user-menu">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <img src="{{ request.user.staff_of.avatar.url }}"
             class="user-image" alt="User Image">
        <span class="hidden-xs">
            {{ request.user.staff_of.real_name|default:request.user.username }}
        </span>
    </a>
    <ul class="dropdown-menu">
        <!-- User image -->
        <li class="user-header">
            <img src="{{ request.user.staff_of.avatar.url }}"
                 class="img-circle" alt="User Image">
            <p>
                您好： {{ request.user.staff_of.real_name|default:request.user.username }}
                {% if request.user.staff_of.real_name %}
                    ({{ request.user.username }})
                {% endif %}
                <small>最近一次登录:{{ request.user.last_login }}</small>
            </p>
        </li>
        <!-- Menu Body -->
        {% comment %}<li class="user-body">
            <div class="col-xs-4 text-center">
                <a href="#">Followers</a>
            </div>
            <div class="col-xs-4 text-center">
                <a href="#">Sales</a>
            </div>
            <div class="col-xs-4 text-center">
                <a href="#">Friends</a>
            </div>
        </li>{% endcomment %}
        <!-- Menu Footer-->
        <li class="user-footer">
            <div class="pull-left">
                <a href="{% url 'change_password' %}"
                   class="btn btn-default btn-flat">
                    修改密码
                </a>
            </div>
            <div class="pull-right">
                <a href="{% url 'registration:logout' %}"
                   class="btn btn-default btn-flat">
                    退 出
                </a>
            </div>
        </li>
    </ul>
</li>

web/core/adminlte/templates/adminlte/includes/header_notifications.html
<!-- Notifications Menu -->
<li class="dropdown notifications-menu">
    <!-- Menu toggle button -->
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <i class="fa fa-bell-o"></i>
        <template v-if="notification | length > 0">
            <span class="label label-success">
            #[ notification | length ]
            </span>
        </template>
    </a>
    <ul class="dropdown-menu">
        <li class="header">
            您有 #[ notification | length ] 条未读系统通知
        </li>
        <li>
            <ul class="menu">
                <template v-for="item in notification">
                    <li>
                        <a href="#">
                            <i class="fa fa-users text-aqua"></i>
                            #[item.title]
                        </a>
                    </li>
                </template>
            </ul>
        </li>
        <li class="footer">
            <a href="{% url 'adminlte:common_list_page' 'messageset' 'notification'%}">
                查看全部系统通知
            </a>
        </li>
    </ul>
</li>

web/core/adminlte/templates/adminlte/includes/header_sitemails.html
<!-- Messages: style can be found in dropdown.less-->
<li class="dropdown messages-menu">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <i class="fa fa-envelope-o"></i>
        <template v-if="sitemailreceive | length > 0">
            <span class="label label-success">
            #[ sitemailreceive | length ]
            </span>
        </template>
    </a>
    <ul class="dropdown-menu">
        <li class="header">您共有 #[ sitemailreceive | length ] 条未读消息</li>
        <li>
            <ul class="menu">
                <template v-for="item in sitemailreceive">
                    <li>
                        <a href="javascript:void(0);" data-pk="#[item.id]"
                                v-on:click="sitemailDetail">
                            <div class="pull-left" data-pk="#[item.id]">
                                <img src="#[item.sender_avatar]"
                                     class="img-circle" alt="User Image"
                                     data-pk="#[item.id]" />
                            </div>
                            <h4 data-pk="#[item.id]">
                                #[item.sender]
                                <small data-pk="#[item.id]">
                                    <i class="fa fa-clock-o"></i> 5 mins
                                </small>
                            </h4>
                            <p data-pk="#[item.id]">#[item.title]</p>
                        </a>
                    </li>
                </template>
            </ul>
        </li>
        <li class="footer">
            <a href="{% url 'adminlte:common_list_page' 'messageset' 'sitemailreceive' %}">
                查看所有消息
            </a>
        </li>
    </ul>
</li>

web/core/adminlte/templates/adminlte/includes/header_tasks.html
<!-- Tasks Menu -->
<li class="dropdown tasks-menu">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <i class="fa fa-flag-o"></i>
        <template v-if="task | length > 0">
            <span class="label label-success">
            #[ task | length]
            </span>
        </template>
    </a>
    <ul class="dropdown-menu">
        <li class="header">
            您有 #[ task | length ] 个正在处理的任务
        </li>
        <li>
            <ul class="menu">
                <template v-for="item in task">
                    <li>
                        <a href="javascript:void(0);" data-pk="#[item.id]"
                                v-on:click="taskDetail">
                            <h3 data-pk="#[item.id]">
                                #[item.name]
                                <small class="pull-right">
                                    #[item.percent]
                                </small>
                            </h3>
                            <div class="progress xs" data-pk="#[item.id]">
                                <div class="progress-bar progress-bar-aqua"
                                     style="width:#[item.percent]"
                                     role="progressbar"
                                     aria-valuenow="#[item.percent|replace '%' '']"
                                     aria-valuemin="0"
                                     aria-valuemax="100">
                                    <span class="sr-only">#[item.percent]</span>
                                </div>
                            </div>
                        </a>
                    </li>
                </template>
            </ul>
        </li>
        <li class="footer">
            <a href="{% url 'adminlte:common_list_page' 'messageset' 'task'%}">
                查看所有任务
            </a>
        </li>
    </ul>
</li>

web/core/adminlte/templates/adminlte/includes/menu.html
{% load mptt_tags %}
<aside class="main-sidebar">
    <section class="sidebar">
        <ul class="sidebar-menu">
            <li class="header">HEADER</li>
            <li {% if request.path_info == '/' %}class="active"{% endif %}>
                <a href="/">
                    <i class="fa fa-dashboard"></i>
                    <span>{{ default_dashboard_title }}</span>
                </a>
            </li>
            {% recursetree page_menus %}
                <li {% if not node.is_leaf_node %}
                        class="treeview {% if node.app_name in request.path_info %} active{% endif %}"
                    {% endif %}>
                    {% if not node.is_leaf_node %}
                        <a href="javascript:void(0)">
                            <i class='fa {{ node.icon }}'></i>
                            <span>{{ node.name }}</span>
                            <i class="fa fa-angle-left pull-right"></i>
                        </a>
                        <ul class="treeview-menu">
                            {{ children }}
                        </ul>
                    {% else %}
                        {% with node.url as menu_url %}
                            {% if not menu_url %}
                                {% url 'adminlte:common_list_page' node.app_name node.model_name as menu_url %}
                            {% endif %}
                            <li {% if menu_url == request.path_info %}
                                    class='active'
                                {% endif %}>
                                <a href="{{ menu_url }}">
                                    <i class="fa {{ node.icon }}"></i>
                                    {{ node.name }}
                                </a>
                            </li>
                        {% endwith %}

                    {% endif %}
                </li>
            {% endrecursetree %}
        </ul>
    </section>
</aside>

web/core/adminlte/templates/adminlte/includes/style.html
<!-- Ionicons -->
<link href="{{ STATIC_PREFIX }}adminlte/css/ionicons.min.css" rel="stylesheet" type="text/css" />
<!-- Bootstrap 3.3.4 -->
<link href="{{ STATIC_PREFIX }}plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
<link href="{{ STATIC_PREFIX }}plugins/sweetalert/dist/sweetalert.css" rel="stylesheet" type="text/css">
<!-- Font Awesome Icons -->
<link href="{{ STATIC_PREFIX }}adminlte/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
<!-- Theme style -->
<link href="{{ STATIC_PREFIX }}adminlte/css/AdminLTE.min.css" rel="stylesheet" type="text/css" />
<link href="{{ STATIC_PREFIX }}adminlte/css/skins/_all-skins.min.css" rel="stylesheet" type="text/css" />
<link href="{{ STATIC_PREFIX }}plugins/iCheck/all.css" rel="stylesheet" type="text/css" />