web/apps/urls.py
# coding=utf-8
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from apps.dashboard.views import IndexView
from core.adminlte.views import ChangePasswordView, \
    ChangePasswordDoneView
from django.views.static import serve
from core.adminlte import views
# 基础 url
urlpatterns = [
    url('^page/change-password/$', ChangePasswordView.as_view(),
        name='change_password'),
    url('^page/change-password-done/$', ChangePasswordDoneView.as_view(),
        name='password_change_done'),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^management/$', login_required(views.IndexView.as_view()), name='manage'),
    url(r'^$', login_required(IndexView.as_view()), name='index'),

    url(r'^auth/', include("core.registration.urls",
                           namespace="registration")),

    url(r'^jsreverse/$', 'django_js_reverse.views.urls_js', name='js_reverse'),
]

# ===================== 自定义url映射 开始====================================
# 自定义url必须放在通用url的前面，将通用url覆盖掉
# Page url
urlpatterns += [
    url(r'^apps/tasks/', include('apps.tasks.urls', namespace='tasks')),
]
# API url
urlpatterns += [
    url(r'^api/', include('apps.api.urls', namespace='api')),
    url(r'^api/v1/messageset', include('core.messageset.urls_api',
                                       namespace='messageset_api')),
    # # url(r'^api/v1/organization', include('organization.urls',
    # namespace='organization_api')),
]

# ===================== 自定义url映射 结束 ==================================

# # 通用URL映射，必须放在最后
urlpatterns += [
    # 通用页面URL映射，必须放在最后
    url(r'^management', include('core.adminlte.urls', namespace='adminlte')),
    url(r'^api/v1', include('core.adminlte.urls_api',
                             namespace='adminlte_api')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        url(r'^page_images/(?P<path>.*)$', serve, {
            'document_root': '/data/share/dzj_characters/page_images',
        }),

    ]

web/core/messageset/urls.py
# coding=utf-8
# from django.conf.urls import include, url
# from django.contrib.auth.decorators import login_required
# from django.views.generic import TemplateView, FormView
# from adminlte.forms import SystemConfigForm
# from .views import SiteMailListView, NotificationListView, \
#     TaskListView
#
#
# # Page URL
# urlpatterns = [
#
#     # url(r'/page/(?P<app_name>\w+)/(?P<model_name>\w+)/form.html$',
#     # TemplateView.as_view(template_name='adminlte/system/config.html'),
#     # name='common_form'),
#     #
#     # url(r'/page/adminlte/SystemConfig.html$',
#     #     TemplateView.as_view(template_name='adminlte/system/config.html'),
#     #     name='systemconfig'),
#     # url(r'/system/config/form.html$', SystemConfigFormView.as_view(),
#     #     name='systemconfig_form'),
#     #
#     # url(r'/system/role.html$', SiteMailListView.as_view(),
#     #     name='role'),
#     # url(r'/system/auth.html$', SiteMailListView.as_view(),
#     #     name='auth'),
#     # url(r'/system/user.html$', SiteMailListView.as_view(),
#     #     name='user'),
#     #
#     # url(r'/page/adminlte/SiteMail.html$', SiteMailListView.as_view(),
#     #     name='sitemail'),
#     # url(r'/notification.html$', NotificationListView.as_view(),
#     #     name='notification'),
#     # url(r'/task.html$', TaskListView.as_view(),
#     #     name='task'),
# ]

web/core/messageset/models.py
# coding=utf-8
import datetime
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse_lazy, reverse
from django.db import models
from django.db.models.signals import post_save, m2m_changed
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.dispatch import receiver
from core.adminlte.constants import ReadStatus, TaskStatus, MailStatus, \
    UsableStatus, TaskType, \
    DICT_NULL_BLANK_TRUE
from core.adminlte.models import BaseModel



class AbstractMessageContent(BaseModel, UsableStatus):
    title = models.CharField(
        verbose_name=u'标题', max_length=200
    )
    contents = models.TextField(
        verbose_name=u'内容'
    )
    status = models.PositiveSmallIntegerField(
        verbose_name=u'状态',
        choices=UsableStatus.STATUS,
        default=UsableStatus.USABLE,
        db_index=True
    )

    class Meta:
        abstract = True


class SiteMailContent(AbstractMessageContent):
    receivers = models.ManyToManyField(
        User, blank=True,
        related_name='sitemail_receivers',
        verbose_name=u'接收人',
        help_text=u'不选则发送给全体用户'
    )

    class Meta:
        verbose_name_plural = verbose_name = u'站内邮件内容'

    def __unicode__(self):
        return self.title

    class Config:
        success_url = reverse_lazy(
            'adminlte:common_list_page',
            kwargs={
                'app_name': 'messageset',
                'model_name': 'sitemailreceive'
            }
        )
        list_form_fields = (
            'title', 'contents', 'receivers'
        )


class AbstractSiteMail(BaseModel, MailStatus):
    title = models.CharField(
        verbose_name=u'主题',
        max_length=200
    )
    content = models.ForeignKey(
        SiteMailContent,
        verbose_name=u'内容'
    )
    sender = models.ForeignKey(
        User,
        related_name='+',
        verbose_name=u'发件人',
        **DICT_NULL_BLANK_TRUE
    )
    send_time = models.DateTimeField(
        verbose_name=u'发送时间',
        auto_now_add=True,
        **DICT_NULL_BLANK_TRUE
    )
    status = models.PositiveSmallIntegerField(
        verbose_name=u'读取状态',
        choices=MailStatus.STATUS,
        default=MailStatus.UNREAD,
        db_index=True
    )

    class Meta:
        abstract = True


class SiteMailSend(AbstractSiteMail):
    def __unicode__(self):
        return u'%s' % self.title

    class Meta:
        verbose_name_plural = verbose_name = u'发件箱'

    class Config:
        detail_template_name = 'messageset/sitemail_detail.html'
        list_display_fields = (
            'title', 'send_time', 'id'
        )
        list_form_fields = (
            'title',
            'content.contents',
            'send_time',
        )
        filter_fields = ('status', )
        search_fields = ('title', )

        @classmethod
        def filter_queryset(cls, request, queryset):
            return queryset.filter(sender=request.user).exclude(
                status=SiteMailSend.DELETED
            )


class SiteMailReceive(AbstractSiteMail):
    receive = models.ForeignKey(
        User,
        related_name='+',
        verbose_name=u'收件人',
        **DICT_NULL_BLANK_TRUE
    )
    read_time = models.DateTimeField(
        verbose_name=u'读取时间',
        **DICT_NULL_BLANK_TRUE
    )

    def __unicode__(self):
        return u'%s' % self.title

    class Meta:
        verbose_name_plural = verbose_name = u'收件箱'

    class Config:
        list_template_name = 'messageset/sitemail_list.html'
        form_template_name = 'messageset/sitemail_form.html'
        detail_template_name = 'messageset/sitemail_detail.html'
        list_display_fields = (
            'title', 'sender',
            'status', 'send_time', 'id'
        )
        list_form_fields = (
            'title', 'sender', 'content.contents'
        )
        filter_fields = ('status', )
        search_fields = ('title', )

        @classmethod
        def filter_queryset(cls, request, queryset):
            return queryset.filter(receive=request.user).exclude(
                status=SiteMailReceive.DELETED
            )
            # if 'receive' in request.query_params \
            # or 'trash' in request.query_params:
            # receive = request.query_params.get('receive', None)
            #     if receive:
            #
            #     trash = request.query_params.get('trash', None)
            #     if trash:
            #         queryset = queryset.filter(
            #             Q(status=SiteMailReceive.DELETED),
            #             Q(sender=request.user) | Q(receive=request.user)
            #         )
            # else:
            #     queryset = SiteMailReceive.objects.none()
            # return queryset

        @classmethod
        def get_object_hook(cls, request, obj):
            save_flag = False
            if obj.status != ReadStatus.READ:
                obj.status = ReadStatus.READ
                save_flag = True
            if not obj.read_time:
                obj.read_time = datetime.datetime.now()
                save_flag = True
            if save_flag:
                obj.save()


class NotificationContent(AbstractMessageContent):
    receivers = models.ManyToManyField(
        User, blank=True,
        related_name='notification_receivers',
        verbose_name=u'接收人',
        help_text=u'不选则发送给全体用户'
    )

    class Meta:
        verbose_name_plural = verbose_name = u'系统通知内容'

    def __unicode__(self):
        return self.title

    class Config:
        success_url = reverse_lazy(
            'adminlte:common_list_page',
            kwargs={
                'app_name': 'messageset',
                'model_name': 'notification'
            }
        )
        list_form_fields = (
            'title', 'contents', 'receivers'
        )


class Notification(BaseModel, ReadStatus):
    title = models.CharField(
        verbose_name=u'标题',
        max_length=200,
        default='',
        **DICT_NULL_BLANK_TRUE
    )
    content = models.ForeignKey(
        NotificationContent,
        verbose_name=u'内容',
        **DICT_NULL_BLANK_TRUE
    )
    receive = models.ForeignKey(
        User,
        related_name='+',
        verbose_name=u'接收人',
        **DICT_NULL_BLANK_TRUE
    )
    status = models.PositiveSmallIntegerField(
        verbose_name=u'读取状态',
        choices=ReadStatus.STATUS,
        default=ReadStatus.UNREAD,
        db_index=True
    )
    send_time = models.DateTimeField(
        verbose_name=u'发送时间',
        auto_now_add=True,
        **DICT_NULL_BLANK_TRUE
    )
    read_time = models.DateTimeField(
        verbose_name=u'读取时间',
        **DICT_NULL_BLANK_TRUE
    )

    def __unicode__(self):
        return u'%s' % self.content.title

    class Meta:
        verbose_name_plural = verbose_name = u'系统通知'

    class Config:
        list_template_name = 'messageset/notification_list.html'
        list_display_fields = (
            'title', 'status', 'send_time', 'id'
        )
        list_form_fields = (
            'title', 'content.contents', 'send_time'
        )
        filter_fields = ('status',)
        search_fields = ('title',)

        @classmethod
        def filter_queryset(cls, request, queryset):
            return queryset.exclude(status=Notification.DELETED).filter(
                receive=request.user
            )

        @classmethod
        def get_object_hook(cls, request, obj):
            obj.status = ReadStatus.READ
            if not obj.read_time:
                obj.read_time = datetime.datetime.now()
            obj.save()




@receiver(m2m_changed, sender=SiteMailContent.receivers.through)
def create_sitemail_datas(sender, instance, **kwargs):
    """
    发送邮件时，向收件箱和发件箱添加数据，
    这里将来可以替换为异步消息队列
    :param sender:
    :param instance:
    :param kwargs:
    """
    kwargs = {
        'title': instance.title,
        'content': instance,
        'sender': instance.creator,
        'creator': instance.creator
    }
    SiteMailSend(**kwargs).save()
    for user in instance.receivers.all():
        tmp_kwargs = {
            'receive': user,
        }
        tmp_kwargs.update(kwargs)
        SiteMailReceive(**tmp_kwargs).save()


@receiver(m2m_changed, sender=NotificationContent.receivers.through)
def create_notification_datas(sender, instance, **kwargs):
    """
    保存系统通知时，给所选用户发送通知，
    目前是向Notification表添加数据
    这里将来可以替换为异步消息队列
    :param sender:
    :param instance:
    :param kwargs:
    """
    for user in instance.receivers.all():
        exists = Notification.objects.filter(
            receive=user, content=instance
        ).exists()
        if not exists:
            nf = Notification()
            nf.title = instance.title
            nf.content = instance
            nf.receive = user
            nf.creator = instance.creator
            nf.status = Notification.UNREAD
            nf.save()

web/core/messageset/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
from __future__ import absolute_import, print_function, unicode_literals
from django import forms

web/core/messageset/views.py
# coding=utf-8

web/core/messageset/templates/messageset/notification_list.html
{% extends "adminlte/common_list.html" %}
{% load static %}

{% block common_list_buttons %}
    {% if request.user and request.user.is_superuser %}
        <button class="btn btn-primary"
                v-on:click="create(event, 'notificationcontent')">
            <i class="fa fa-plus"></i>
            发布新通知
        </button>
    {% endif %}
    <button class="btn btn-danger"
            v-on:click="removeSelected">
        <i class="fa fa-trash-o"></i>
        删除
    </button>
{% endblock %}

{% block common_list_page_show_modify %}
{% endblock %}

web/core/messageset/templates/messageset/sitemail_detail.html
{% extends "adminlte/common_detail.html" %}
{% load adminlte_tags %}


{% block breadcrumb %}
    <ol class="breadcrumb">
        <li>
            <a href="/">
                <i class="fa fa-dashboard"></i> {{ default_dashboard_title }}
            </a>
        </li>
        {% if page_title != default_dashboard_title %}
            <li class="active">
                <a href="{% url 'adminlte:common_list_page' page_app_name 'sitemailreceive' %}">
                    站内信
                </a>
            </li>
        {% endif %}
        {% if object != None %}
            <li class="active">详情</li>
        {% endif %}
    </ol>
{% endblock %}

web/core/messageset/templates/messageset/sitemail_form.html
{% extends "adminlte/base.html" %}

{% block content_title %}
    发送{{ page_title }}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-6">
                            {% if form.is_multipart %}
                                <form enctype="multipart/form-data"
                                      method="post"
                                      action=""
                                      role="form" id="commonForm">
                            {% else %}
                                <form method="post" action=""
                                      role="form" id="commonForm">
                            {% endif %}
                            {% csrf_token %}
                            {% for field in form %}
                                {% if field.name == 'sender' %}
                                    <input id="id_sender" name="sender"
                                           type="hidden"
                                           value="{{ request.user.id }}">
                                {% else %}
                                    <div class="form-group">
                                        {{ field.label_tag }}
                                        {{ field }}
                                        <p class="help-block">{{ field.help_text }}</p>
                                    </div>
                                {% endif %}
                            {% endfor %}
                            <div class="clearfix"></div>
                            <button type="submit" class="btn btn-primary">
                                保 存
                            </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block base_foot_script %}
    <script type="text/javascript">
        $('#commonForm input:text').addClass('form-control');
        $('#commonForm select').addClass('form-control');
        $("#commonForm select > option[value='{{ request.user.id }}']").remove();
        $('#commonForm textarea').addClass('form-control');
    </script>
{% endblock %}

web/core/messageset/templates/messageset/sitemail_list-back.html
{% extends "adminlte/common_list.html" %}
{% load static %}
{% block common_list_buttons %}
    <button class="btn btn-primary"
            v-on:click="create">
        <i class="fa fa-pencil"></i>
        写信
    </button>
    <button class="btn btn-link"
            v-on:click="allStatus">
        全部
    </button>
    <button class="btn btn-link"
            v-on:click="unReadStatus">
        未读
    </button>
    <button class="btn btn-link"
            v-on:click="readStatus">
        已读
    </button>
    <button class="btn btn-link"
            v-on:click="markAllRead">
        全部标记为已读
    </button>
    <button class="btn btn-link"
            v-on:click="removeSelected">
        <i class="fa fa-trash-o"></i>
        删除
    </button>
{% endblock %}


{% block common_list_foot_page_script %}
    <script src="{% static 'messageset/js/sitemail-list-page.js' %}"
            type="text/javascript"></script>
{% endblock %}

web/core/messageset/templates/messageset/sitemail_list.html
{% extends "adminlte/common_list.html" %}
{% load static %}

{% block content_title %}
    站内信
{% endblock %}

{% block breadcrumb %}
    <ol class="breadcrumb">
        <li>
            <a href="/">
                <i class="fa fa-dashboard"></i> {{ default_dashboard_title }}
            </a>
        </li>
        {% if page_title != default_dashboard_title %}
            <li class="active">
                <a href="{% url 'adminlte:common_list_page' page_app_name 'sitemailreceive' %}">
                    站内信
                </a>
            </li>
        {% endif %}
    </ol>
{% endblock %}

{% block content %}
    <div class="row" id="siteMailContentRow">
        <div class="col-md-3">
            <a href="javascript:void(0);" v-on:click="newMail"
               class="btn btn-primary btn-block margin-bottom">
                <i class="fa fa-pencil"></i> 写信</a>

            <div class="box box-solid">
                <div class="box-header with-border">
                    <h3 class="box-title">文件夹</h3>

                    <div class="box-tools">
                        <button class="btn btn-box-tool"
                                data-widget="collapse"><i
                                class="fa fa-minus"></i></button>
                    </div>
                </div>
                <div class="box-body no-padding">
                    <ul class="nav nav-pills nav-stacked">
                        <li class="active">
                            <a href="javascript:void(0);" v-on:click="inBox">
                                <i class="fa fa-inbox"></i> 收件箱
                                <span v-if="unReadItemsCount > 0"
                                      class="label label-primary pull-right">
                                    #[unReadItemsCount]
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="javascript:void(0);" v-on:click="sendBox">
                                <i class="fa fa-envelope-o"></i> 发件箱
                            </a>
                        </li>
                        {#                        <li>#}
                        {#                            <a href="#">#}
                        {#                                <i class="fa fa-file-text-o"></i> 草稿箱#}
                        {#                            </a>#}
                        {#                        </li>#}
                        {#                        <li>#}
                        {#                            <a href="javascript:void(0);" v-on:click="trashBox">#}
                        {#                                <i class="fa fa-trash-o"></i> 垃圾箱#}
                        {#                            </a>#}
                        {#                        </li>#}
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-9">
            <div class="row">
                <div class="box">
                    <div class="box-header">
                        <div class="row">
                            <div class="col-xs-12 col-sm-8">
                                {% comment %}<button class="btn btn-primary"
                                        v-on:click="allStatus">
                                    全部
                                </button>
                                <button class="btn btn-link"
                                        v-on:click="unReadStatus">
                                    未读
                                </button>
                                <button class="btn btn-link"
                                        v-on:click="readStatus">
                                    已读
                                </button>
                                <button class="btn btn-link"
                                        v-on:click="markAllRead">
                                    标记为已读
                                </button>{% endcomment %}
                                <div class="checkbox pull-left btn-link"
                                     style="margin-top: 7px; margin-right: 12px;">
                                    <label>
                                        <input type="checkbox"
                                               name="checkboxAllRow"
                                               v-on:click="toggleAllBox"/> 全选
                                    </label>
                                </div>
                                <button class="btn btn-link"
                                        v-on:click="removeSelected">
                                    <i class="fa fa-trash-o"></i>
                                    删除
                                </button>
                            </div>
                            <div class="col-xs-12 col-sm-4">
                                <div class="input-group">
                                    <input type="text" name="search"
                                           id="tableSearch"
                                           class="form-control input-sm pull-right"
                                           style="width: 150px;"
                                           placeholder="邮件标题关键字"
                                           v-on:keypress.13="search">

                                    <div class="input-group-btn">
                                        <button class="btn btn-sm btn-default"
                                                v-on:click="resetSearch">
                                            <i class="fa fa-times-circle"></i>
                                        </button>
                                        <button class="btn btn-sm btn-default"
                                                v-on:click="search">
                                            <i class="fa fa-search"></i>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body table-responsive no-padding">
                        <table class="table table-hover" id="commonTable">
                            <tbody>
                                <template v-for="item in items">
                                    <tr>
                                        <td style="width:40px;text-align:center">
                                            <input type="checkbox"
                                                   class="minimal"
                                                   name="checkboxRow"
                                                   value="#[item.id]"/>
                                        </td>
                                        {% for field in table_fields %}
                                            {% if field == 'id' %}
                                                <td>
                                                    <a href="javascript:void(0);"
                                                       data-pk="#[item.id]"
                                                       v-on:click="detail">
                                                        详情
                                                    </a> |
                                                    <a href="javascript:void(0);"
                                                       data-pk="#[item.id]"
                                                       v-on:click="removeOne">
                                                        删除
                                                    </a>
                                                </td>
                                            {% else %}
                                                <td>
                                                    {!! item.{{ field }} !!}
                                                </td>
                                            {% endif %}
                                        {% endfor %}
                                    </tr>
                                </template>
                                </template>
                            </tbody>
                        </table>
                    </div>
                    {% block common_list_pagination %}
                        <div class="box-footer clearfix">
                            {% include 'adminlte/common_list_pagination.html' %}
                        </div>
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block base_foot_page_script %}
    <script src="{% static 'adminlte/js/common-list-page-base.js' %}"
            type="text/javascript"></script>
    <script src="{% static 'messageset/js/sitemail-list-page.js' %}"
            type="text/javascript"></script>
{% endblock %}

web/core/messageset/templates/messageset/task_detail.html
{% extends "adminlte/base.html" %}
{% load adminlte_tags %}

{% block content_title %}
    {{ page_title }}详情
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <div class="box">
                <div class="box-body table-responsive no-padding">
                    {% for field in object.Config.list_form_fields %}
                        <table class="table">
                        {% ifnotequal field 'id' %}
                            <tr>
                                <th style="width:100px;">{{ object|render_field_label:field }}:</th>
                                <td>{{ object|render_field_value:field|safe }}</td>
                            </tr>
                        {% endifnotequal %}
                        </table>
                    {% endfor %}
                </div>
            </div>
            <a class='btn btn-primary'>开始任务</a>
        </div>
    </div>
{% endblock %}

web/core/messageset/templates/messageset/task_list.html
{% extends "adminlte/common_list.html" %}
{% load static %}

{% block common_list_buttons %}
    <button class="btn btn-danger"
            v-on:click="removeSelected">
        <i class="fa fa-trash-o"></i>
        删除
    </button>
{% endblock %}